name: ipod2
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python
    - bedtools
    - numpy
    - pandas
    - statsmodels
    - scipy
    - samtools
    - cutadapt
    - trimmomatic
    - matplotlib
    - toml
    - fastqc
    - tk
    - numba
    - bunch
    - scikit-learn
    - h5py
    - ipython
