name: ipod
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python
    - pip
    - bedtools
    - numpy
    - bowtie2=2.4.4
    - pandas
    - statsmodels
    - scipy
    - samtools
    - cutadapt
    - trimmomatic
    - matplotlib
    - toml
    - fastqc
    - tk
    - numba
    - bunch
    - scikit-learn
    - h5py
    - ipython
    - mummer
    - pip:
        - recombinator
